### PR TITLE
Support for gcd and lcm of rational numbers.

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by pdimov** [comment]
This should probably be updated now that gcd/lcm are in Integer.

**Comment by mclow** [comment]
I like this, but I'm not seeing any tests.

**Comment by mlang** [comment]
Marshall Clow notifications@github.com writes:

> I like this, but I'm not seeing any tests.

Mathematicians keep telling me that gcd on rational numbers is sort of
undefined.
Still, I have a use-case for it, and it behaves exactly as
expected/required.  It is rather easy to drop these two specialisations
in your own headers, but I think it would be more convenient if rational
already provided it out of the box.

## 

CYa,
  ⡍⠁⠗⠊⠕

**Comment by mclow** [comment]
> It is rather easy to drop these two specialisations
> in your own headers, but I think it would be more convenient if rational
> already provided it out of the box.

I'm not disputing that; but before we put it into boost, we need some tests to make sure it is correct - and even more importantly, make sure it doesn't get broken by changes in boost or the environment.

**Comment by mlang** [comment]
Tests added.

**Pull request merged**
