### PR TITLE
Merge branch 'no-float-convert' of https://github.com/jzmaddock/ratio…

### PR DESCRIPTION
**Pull request by jzmaddock**
…nal into develop

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.

### CODE REVIEW

**Comment by jzmaddock** [comment]
This is PR #4 with changes from develop merged in.

**Comment by jzmaddock** [comment]
Can you let me know if you plan to merge this to master?  There are some workarounds in Multiprecision which need removing to ensure the 2 libraries continue to interoperate, and it's inconvenient to have master and develop diverge.  Thanks!

**Comment by eldiener** [comment]
I had already merged this to master.

**Comment by jzmaddock** [comment]
> I had already merged this to master.
>

Doh!  So you have, sorry for the noise, John.

**Comment by eldiener** [comment]
Evidently such constructors as boost::rational<int>(1u,1) are now illegal. Was this intended ?

**Comment by jzmaddock** [comment]
On 26/03/2017 13:20, Edward Diener wrote:
>
> Evidently such constructors as boost::rational(1u,1) are now illegal. 
> Was this intended ?
>

As I mentioned on the mailing list, no not intentional.

The direct patch for that issue is more or less trivial.  However, 
looking at the code and tests I can see a whole bunch of related stuff 
which either isn't being tested and/or which looks suspect. I'll get a 
PR in as a matter of urgency.

John.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by eldiener** [comment]
Thanks, John. This is on me also for merging the PR. I naively assumed that the tests, which passed with your fix, covered all the important possibilities, so I blindly trusted the fix to be correct and also because it came from you.

**Comment by jzmaddock** [comment]
On 26/03/2017 18:47, Edward Diener wrote:
>
> Thanks, John. This is on me also for merging the PR. I naively assumed 
> that the tests, which passed with your fix, covered all the important 
> possibilities, so I blindly trusted the fix to be correct and also 
> because it came from you.
>

Trust no one! ;)

Part of the problem is that rational had rather few tests and was very 
poorly specified in terms of what should happen in converting 
constructors.... testing fixes now.

John.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Pull request merged**
