### PR TITLE
Expand Travis CI for more coverage

### PR DESCRIPTION
**Pull request by tonyelewis**
Some tests have failed in another branch and PR. It'd be good to be
confirm whether those tests pass without that branch's changes.

### CODE REVIEW

**Comment by jeking3** [comment]
The UBSAN issue looks like something in Boost.Test.  I have [reported it](https://github.com/boostorg/test/issues/174).

**Comment by jeking3** [comment]
Not much point in diagnosing the compiler error here; should disable the gcc 4.6 job in the .travis.yml file - that just leaves the UBSAN issue.

**Comment by tonyelewis** [comment]
Closing this pull-request because it has now served its purpose of checking build failures.

**Comment by jeking3** [comment]
I'll finish the update on my end - thanks.

**Pull request closed without merging**
